### ISSUE TITLE
[Feature Request] Add facility to add text after parts list in readme.html

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#114]
Quite often it is useful to add text after the parts list, for example to describe possible alternatives for parts, or where to source difficult to obtain parts.

**Comment by nophead** [comment]
When we were selling 3D printer kits I had a script that put the parts into a spread sheet where I added URLs to shops and prices to get a costed BOM. It used OpenOffice.

**Comment by nophead** [comment]
Perhaps we could split the blurb by looking for the first point number or bullet point as the start of the build instructions. Any lines before that go before the Assembly Instructions heading. Or would you prefer them just after the vitamins list?

**Comment by nophead** [comment]
I think a markdown horizontal rule would be a better way of splitting the blurb into procurement instructions and build instructions.

The first rule itself would be omitted but anything before it would be rendered after the vitamin list and anything after it as build instructions.

**Comment by martinbudden** [comment]
There are 4 main places to place text:

1. At the very beginning of the readme.
2. In the first section of the readme, but after the picture
3. After the table of contents
4. After the Parts list

It would be useful to be able put text into each of those positions. I think using a horizontal rule as the demarcation works fine.

It would also be useful to specify that the picture is omitted, so that you can put in your own alternative picture.

**Comment by nophead** [comment]
Oh good job you clarified because I thought you meant after the vitamins in each assembly step rather than the top level parts list.

**Comment by nophead** [comment]
It currently uses assemblies/main_assembled.png for the cover picture. I could look in doc for a file with the same name and use that instead if it exists and also look for .jpg.

**Comment by nophead** [comment]
Are you wanting to replace the cover picture with a photo, or another generated image?

I could just omit the picture if it finds a markdown image tag in the first section of the blurb but it sort of confuses the before and after picture description of where the blurb goes. Would it expect one less section when it finds the first section contains an image?

**Comment by martinbudden** [comment]
My current thinking is to replace the cover picture with another generated image alongside a photo.

I think the easiest thing is to omit the before and after the picture blurb. If I want blurb after the picture then I can manually insert the picture and have blurb before and after.

So I think we now have the following positions for blurb:

1. At the beginning of the readme. If no image tag in the markdown then the picture is auto-generated, if an image tag is found, then no picture is generated. 
2. After the table of contents
3. After the Parts List

**Comment by nophead** [comment]
I pushed a change which I think does what you want. See https://github.com/nophead/NopSCADlib/commit/8d22940506df525ac52ef6f8a00ea03661f3b682

**Comment by martinbudden** [comment]
Great, thanks. I'll check it out.

**Comment by nophead** [comment]
Note I only look for ***, so if you want a horizontal rule to appear use ---

**Comment by martinbudden** [comment]
Yes, I noticed you only look for `***`, I was going to ask you to change it, but on second thoughts it works well the way it is, `---` for a horizontal rule, `***` to separate sections.

So I've tried this, and it works fine.

One minor thing, can you also allow any number of asterisks, ie so that you can have a line of `*************` for the separation, as per markdown syntax.

**Comment by nophead** [comment]
Done via https://github.com/nophead/NopSCADlib/commit/4ea08839652e02c42fb033006dde372e01937ac4

**Comment by martinbudden** [comment]
Great, thanks. I think this issue can be closed now.
