### ISSUE TITLE
Define hierarchy.

### ISSUE THREAD

**Issue by zignig** [nophead/NopSCADlib#119]
is there a way to grok a tree from here? Openscad is good but the taxonomy is actually more distinct. #CADQUERY #CQPARTS

**Comment by nophead** [comment]
I don't fully understand the question.

This library can create a hierarchy of assemblies that use other assemblies and vitamins. From this a hierarchical bill of materials is generated and a structured readme document that shows each assembly exploded, the parts that make it and the assembly instructions.
