### ISSUE TITLE
error when make_all

### ISSUE THREAD

**Issue by SmoothieAq** [nophead/NopSCADlib#152]
Downloaded NopSCADlib today, gets:

![Capture](https://user-images.githubusercontent.com/58971930/108626812-72f91980-7452-11eb-992e-6ef200b43880.PNG)

And similar with stls/printed/times.txt

If I manually create the missing directories it works.

**Comment by nophead** [comment]
Whoops, the folder should not be needed when there are no panels or platters. Should be fixed by https://github.com/nophead/NopSCADlib/commit/e0b89359aabb05a5c35f85a4036a1d055a02e4ad
