### ISSUE TITLE
feature request: wing nuts

### ISSUE THREAD

**Issue by buttim** [nophead/NopSCADlib#198]
They are quite bulky, so something to definitely take into account when designing a 3D model

**Comment by nophead** [comment]
There is already a wingnut:

![image](https://user-images.githubusercontent.com/566149/133428488-8c1b65ac-2026-4b09-ae4b-a76c56a2e3ba.png)

M4 because that is what I used for Mendel90 but is is fully parametric, so other sizes could be added.

**Comment by buttim** [comment]
Sorry about that. I searched in the README and could not find the word "wing". Shame on me
