### ISSUE TITLE
Suggested improvement to NEMA stepper motor naming convention

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#217]
Currently stepper motors of a given size are differentiated by a suffix, eg NEMA17, NEMA17S, NEMA17M etc, however it's not really that clear what each suffix means. I suggest that instead the suffix reflects their length, eg NEMA17_40, NEMA17_24, NEMA17_60 etc.

Additionally stepper motors with an integrated lead screw should have a suffix reflecting this. So a 40mm long NEMA17 with a 250mm lead screw would be NEMA17_40L250, etc.

If you agree, I can submit a PR for this.

**Comment by nophead** [comment]
Yes I think that would be better,

**Comment by nophead** [comment]
Implemented by #218
