### ISSUE TITLE
Build unnecessarily compares tiny (_tn) images

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#232]
The build process compares the `_tn` images and then deletes the difference files. Although the `_tn` files are small and so quicker to compare, it still takes time and slows down the build.

**Comment by nophead** [comment]
The magic compares typically take around 100ms, so I don't see any reason to change this. OpenSCAD takes nearly 2 seconds to do nothing and often takes minutes, so it totally dwarfs the times.

In a build that takes 423 seconds to do the assembly images it only took 2 seconds to do all the small image compares and 6.7 to do the large ones.

**Comment by nophead** [comment]
I just pushed a change that logs all the command times in cmd_times.txt.

Please can you confirm the times to run magick are negligible on your system as well.
