### ISSUE TITLE
Should polyholes and teardrops be in core?

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#233]
Currently `polyholes.scad` and `teardrops.scad` are included in `utils/global.scad` which is included in `utils/core.scad`.

I don't think polyholes and teardrops are core - they are only used in printed objects, not vitamins.

I think test have shown that the parsing of include files does have an impact on build times, so I think these two files should be move out of core.

Thoughts?

**Comment by martinbudden** [comment]
No, they are included.

**Comment by nophead** [comment]
That is because global.scad is only `use`d. So all the includes in it get pasted together, parsed once and cached as one entry in the module cache.

**Comment by nophead** [comment]
I am minded to close this as I don't think parsing these two files once per build is significant and they are probably used in some vitamins that have modules to make mounting holes for themselves.
