### ISSUE TITLE
Countersunk hole for 3D printed part?

### ISSUE THREAD

**Issue by ganzgustav22** [nophead/NopSCADlib#242]
I'm trying to make a countersunk hole for 3D printed parts.

I've read the documentation here, but it doesn't seem to have an explanation or example on how to call the function.
https://hydraraptor.blogspot.com/2020/12/sinkholes.html

I've downloaded the NopSCADlib, extracted it, put it into a subdir and included it like this:
`include <NopSCADlib/lib.scad>
`
Now I wanted to make a countersunk hole, like this:
`screw_polysink(type = hs_cs, h = 100, alt = false, sink = 0);`

But I get warnings and an error:

![image](https://user-images.githubusercontent.com/62015309/195053257-93be6a04-3ee1-42c7-b8db-900460979d11.png)

Could somebody please give a hint of maybe what I might be doing wrong?

**Comment by nophead** [comment]
The type parameter should be a screw with a countersunk head, not a screw head type.

**Comment by ganzgustav22** [comment]
d'ohhh. Now with "type = M3_cs_cap_screw" it works. Thanks a lot :)

**Comment by nophead** [comment]
No problem. Most of my modules and functions that operate on objects have a `type` parameter. It is like `self` in Python or `this` in C++. Perhaps type was not the best name for it but too late to change now.
