### ISSUE TITLE
[Feature Request] Please add oscillator crystals

### ISSUE THREAD

**Issue by LenStruttmann** [nophead/NopSCADlib#249]
Please add oscillator crystals.
Such as: 
https://www.digikey.com/en/products/detail/ecs-inc./ECS-240-20-4DN/281767?utm_adgroup=Crystals&utm_source=google&utm_medium=cpc&utm_campaign=Shopping_Product_Crystals%2C%20Oscillators%2C%20Resonators_NEW&utm_term=&utm_content=Crystals&gclid=Cj0KCQiAic6eBhCoARIsANlox86G0ai6fUx_7o-KqEQVTIYLmhD-CWUmuOvdPNFnlOaLalONcJGrKksaAlB8EALw_wcB

Thanks!

**Comment by nophead** [comment]
![image](https://user-images.githubusercontent.com/566149/215735612-e4f0d6a5-7915-449c-9711-d428e5ed82b4.png)

![image](https://user-images.githubusercontent.com/566149/215735777-d2574c30-6879-4ab4-a231-6805f249aa4c.png)


Needs a bit more work to handle cylindrical ones and oscillator modules but I will merge it soon.

**Comment by LenStruttmann** [comment]
Awesome!

**Comment by LenStruttmann** [comment]
And, if you have time, could you add a SOIC14?  There are two on this HC-SR04 module that I'm modelling.
https://createc3d.com/783-large_default/buy-hc-sr04-ultrasonic-sensor-price-offer.webp

**Comment by nophead** [comment]
Implemented by df06d1f57fff64cd6da20684f8371da204f69a82
