### ISSUE TITLE
Collaboration on Web Based Hosting of This Project with Real-Time Openscad

### ISSUE THREAD

**Issue by ishapiro** [nophead/NopSCADlib#256]
Sorry for posting here if it is in the wrong place.   I couldn't figure out a better way to get in touch.  Our team has built a web-based OpenSCAD environment with 5,000+ registered users and would love to collaborate with you on making your scripts readily available on the platform.   

You can learn about this at models.makewithtech.com

This OpenSCAD environment fully supports the use of modules and the customizer.  The trick is to put your supporting files in a zip file and upload them with your primary SCAD script.  Then the primary script can use any file in the exploded zip folder structure.

We are releasing updates to the web environment often. Our team would be happy to consider any custom updates that would optimize the availability of your work to a wide range of users uncomfortable with installing OpenSCAD locally.

While models.makewithtech.com is a for-profit company, the basic online OpenSCAD customizer and access to thousands of models will always be free.   We are committed to expanding the OpenSCAD community with script hosting (we call scripts templates), a working and fast customizer, and an online OpenSCAD IDE.

**Comment by nophead** [comment]
I see you are shutting down your service so I am closing this.

This is a library to make projects, not an actual project anyway. All my projects use this library, so it would mean uploading a zipped version with each of them, which is not very practical. 

I also don't use the customizer to customise my models, I instead use it to enable and disable items in the assembly view.

To publish a project I just use Github. See https://github.com/nophead/Blinder. This library generates the readme file for the project.
