### ISSUE TITLE
ERROR: Parser error: syntax error in file splines.scad, line 96 

### ISSUE THREAD

**Issue by maxmay6666** [nophead/NopSCADlib#276]
Hallo,
I get the error: [ERROR: Parser error: syntax error in file splines.scad, line 96](https://github.com/nophead/NopSCADlib/issues/96,C:/Users/win10/Documents/OpenSCAD/libraries/NopSCADlib/utils/splines.scad)

thank you for the lib

Uli

**Comment by nophead** [comment]
There is a trailing comma in the let on the previous line, which is allowed in recent versions of OpenSCAD but not the last release. I will fix it later today.

**Comment by nophead** [comment]
Fixed via 870b396574935603305462f1fea88564c909aad8
