### ISSUE TITLE
sweep.scad: error in line 283 caused by comma at end of line 281

### ISSUE THREAD

**Issue by WernerP** [nophead/NopSCADlib#284]
When starting OpenSCAD using files in directory examples, I get an error message "[ERROR: Parser error: syntax error in file ../utils/sweep.scad, line 283]. In file sweep.scad there is a comma at the end of line  281. Removing it, solves the problem

**Comment by nophead** [comment]
You must be using an older version of OpenSCAD than me. I will fix it.

**Comment by WernerP** [comment]
Sorry, I forgot to add the OpenSCAD version I use:

I am using OpenSCAD version 2021.01

Bye

WernerP

**Comment by nophead** [comment]
Fixed by a483494da97c258507fbd17060866a4bed5a9025
