### ISSUE TITLE
non-standard markdown

### ISSUE THREAD

**Issue by SmoothieAq** [nophead/NopSCADlib#29]
The generated markdown does not show nicely in all viewer.

Tables should have at least 3 dashes, eg not `|:--|` but better `|:---|`.

Would you like a PR? I have also made a carbon tube, would you like PR for stuff like that?

**Comment by nophead** [comment]
Yes please. Which viewer doesn't like it?

**Comment by SmoothieAq** [comment]
I use IntelliJ for OpenSCAD development, and its markdown viewer is quite strict.

In general I find that https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet has only examples that works in all viewers.

I currently work on some new vitamins, and will make a couple of PRs later; might take a week or two.

**Comment by nophead** [comment]
I have fixed this via https://github.com/nophead/NopSCADlib/commit/b559319b0337ed0f1c1e0faa432bf84277e16ecc
