### ISSUE TITLE
No threads on stepper motor boltholes

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#55]
I don't think you've added threads to the bolt holes on the stepper motor.

**Comment by nophead** [comment]
Yes there are few things yet to get thread. Stepper aren't a priority because they are normally shown with screws in them.

**Comment by martinbudden** [comment]
I thought I'd mention it in case you overlooked them.

**Comment by nophead** [comment]
Fixed via https://github.com/nophead/NopSCADlib/commit/bcff26a27b164b198d49982b7eb7f2c96dec0a84

**Comment by martinbudden** [comment]
Great. Although I didn't expect it, adding threads does make the assembly instructions clearer.
