### ISSUE TITLE
Blowers do not have bolt holes

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#59]
Not generally a problem for assemblies, but it does make the exploded view in build instructions look a bit odd. For efficiency it would be possible to only show the bolt hole in the exploded view.

**Comment by nophead** [comment]
Just a bug that they weren't there. Fixed via https://github.com/nophead/NopSCADlib/commit/1a197ac823edbb95063f0cf2ea68f952c8e2c61d
