### ISSUE TITLE
SHOW_THREADS environment variable not uniquified

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#61]
Using `SHOW_THREADS ` means there is a possible (although unlikely) clash with another program. Also, if anyone lists their environment variables, it's not obvious what program uses `SHOW_THREADS`. I suggest it is changed to `NOPSCADLIB_SHOW_THREADS `.

**Comment by nophead** [comment]
Fixed by https://github.com/nophead/NopSCADlib/commit/c815c1592d690812b42b821273766612dae4b1f5
