### ISSUE TITLE
Unnecessary use of `height` named parameter in `linear_extrude`

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#70]
The use of the `height` named parameter in `linear_extrude` is unnecessary and results in oddities such as `linear_extrude(height = thickness)`,  `linear_extrude(height = depth)` and `linear_extrude(height = length)`.  These would read better as `linear_extrude(thickness)`,  `linear_extrude(depth)` and `linear_extrude(length)`.

**Comment by nophead** [comment]
Yes that would be better.

**Comment by nophead** [comment]
Fixed via https://github.com/nophead/NopSCADlib/commit/e8abcde52f266b0ebdcc13fd6f3050658bc3a4ad
