### ISSUE TITLE
[Feature Request]  Add MGN12H carriage

### ISSUE THREAD

**Issue by mak0t0san** [nophead/NopSCADlib#76]
Could be as simple as adding this to rails.scad:
`MGN12H_carriage =[ 45.4, 32.4, 27, 13, 3,   20, 20, M3_cap_screw ];`

and 

`MGN12H= [ "MGN12H", 12, 8,   10,  25, 6.0, 3.5, 4.5, M3_cap_screw,   MGN12H_carriage, M3_cs_cap_screw ];`

**Comment by nophead** [comment]
Yes, done.
