### ISSUE TITLE
libtest.scad compile error

### ISSUE THREAD

**Issue by stuphi** [nophead/NopSCADlib#77]
Had an error when running libtest.scad on a Linux machine running OpenSCAD 2019.05
I changed line 76 to use a capital S as follows: `use <tests/Swiss_clips.scad>` and the error went away.

**Comment by nophead** [comment]
Fixed via https://github.com/nophead/NopSCADlib/commit/9f4ed2b9155571a6e538a7195b9f8b10cabf7113.

Thanks, I guess you are on Linux then!

**Comment by nophead** [comment]
Or perhaps Mac.
