### ISSUE TITLE
Lead nuts should be brass coloured

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#86]
Currently lead nuts are a dark grey. Shouldn't they be brass coloured?

**Comment by nophead** [comment]
Mine are POM, so actually black. I model black with dark grey as OpenSCAD black is a true black body.

**Comment by nophead** [comment]
Brass would give backlash as it would need clearance. POM is tight, at least to start with.

**Comment by martinbudden** [comment]
True, they were brass coloured, then you'd want to add an anti-backlash type with spring to the library. So the colour change can wait until someone implements an anti-backlash lead nut.

Closing.
