### ISSUE TITLE
Belt gap does not allow a belt to be offset with itself at the gap positon.

### ISSUE THREAD

**Issue by martinbudden** [nophead/NopSCADlib#91]
This is required, for example in certain forms of coreXY. See image, the current belt gaps are highlighted in pink.
![CoreXY](https://user-images.githubusercontent.com/194586/99070519-4c505a80-25a8-11eb-928a-043c75cedb8e.png)

Fix will be submitted soon.

**Comment by nophead** [comment]
Interesting. Is that core XY with two separate planar belts? I thought it had one belt in a spiral normally. I wouldn't like to model that so use H-BOT myself! I don't think the racking force matters with trapezoidal rails. I have a milling machine with a single Y axis ball screw in the middle. I have yet to test my H-BOT though.

**Comment by martinbudden** [comment]
Yes, that is coreXY. CoreXY always uses two belts, although there are different ways they can be offset from each other. It's not that difficult to model. Here's the top view with the fix (and you can see why I wanted the JST connectors on the motors).
![CoreXYfix](https://user-images.githubusercontent.com/194586/99071865-db5e7200-25aa-11eb-97b1-23324e2150e6.png)

**Comment by martinbudden** [comment]
And for your interest, here's current state of the project:
![HIGLR_main](https://user-images.githubusercontent.com/194586/99072878-c4208400-25ac-11eb-938e-a0bf52bed06a.png)

**Comment by nophead** [comment]
Not sure what is happening to your latest commit to the PR. I see this:

![image](https://user-images.githubusercontent.com/566149/99115673-b853b280-25ea-11eb-9d77-62e52cf5d290.png)

If I click on the commit number in the email I get this:

![image](https://user-images.githubusercontent.com/566149/99115815-ecc76e80-25ea-11eb-8abf-08629e7619be.png)

**Comment by martinbudden** [comment]
I think I made a mistake when rebasing. It should be ok now.

**Comment by nophead** [comment]
Seems there are two ways of doing coreXY. From the Reprap wiki:

>There is two ways to built the CoreXY belt system.
>
>Both belts are on same plane so belts are crossing and they tend to rub one against the other at crossing point. Twisting the belt on the crossing path limits the rubbing. A small finger can be installed to separate the belts at crossing point.
>The two belts could be set on two different levels (see image). This creates a small tilting momentum on the hotend carriage and increase the momentum on shafts if pulleys are installed on cantilevered shafts. This also save some space on the return pulley side as the pulleys could be stacked.

It would be difficult to model the second type because the path is no longer 2D.

**Comment by martinbudden** [comment]
Yes, modelling the second type would be difficult in NopSCADlib.

And among the two types, there are many variations.
